# ==========================================
# Station Configuration
# ==========================================

# Define connectivity for all physical hardware units
link:
  # --- MAIN DUT: Primary Device Under Test ---
  main_dut:
    type: ssh                # Connection type: supports ssh, adb, com
    host: 192.168.1.110      # Device IP address
    user: kumamodo           # Login username
    password:                # Login password
    stop_chars: ':~$'        # [Optional] Shell prompt termination characters

  main_mcu:
    type: "udp"
    host: "192.168.1.111"
    server_port: 5088
    client_port: 5088